### ISSUE TITLE
Bencode enum link in the readme is broken

### ISSUE THREAD

**Issue by dtolnay** [toby/serde-bencode#11]
Currently points to https://github.com/toby/serde-bencode/blob/master/src/bencode_enum.rs

**Comment by chpio** [comment]
i would just move all infos from the readme to rustdocs (thus remove them from readme) & link to docs.rs

**Comment by toby** [comment]
I agree with @chpio about docs.rs. I'll open a separate issue for that, remove the outdated readme info for now and close this issue.
