### ISSUE TITLE
Write better documentation

### ISSUE THREAD

**Issue by toby** [toby/serde-bencode#12]
We should be using better (some!) source code annotations to generate documentation for rustdoc/docs.rs.

**Comment by TopologicallySpeaking** [comment]
I've started working on this. I have a couple questions, though.

1. What kind inputs cause errors with `ser::to*` and `de::from*`? For example, according to [`serde_json`'s](https://docs.serde.rs/serde_json/fn.to_string.html) documentation, it fails when trying to serialize a map with non-string keys.
2. There are a few data types that seem like they should not be part of the public api. Right now, I have them annotated with `#[doc(hidden)]`, but I want to double check whether that's a good idea. The types I'm referring to are `SerializeMap`, `BencodeAccess` and `StringSerializer`. If these are, in fact, not part of the public api, then it should instead be listed as `pub(crate)`.

**Comment by toby** [comment]
Thank you for this! Honestly, I haven't had time to work on this library for years so am not up to date with the latest from Serde. If you want to take a stab at how this would work, I'll happily review it and merge.

**Comment by TopologicallySpeaking** [comment]
Alright, I think I was able to reasonably guess what errors should be listed. I've finished the doc comments for all the public interfaces. Should I add comments inside the more complex functions or just doc comment annotations?

**Comment by TopologicallySpeaking** [comment]
Scratch that, I don't think there are any functions long enough to warrant any more work. I'll set up the pull request.
