### ISSUE TITLE
Encoding Vec<u8> as bytes

### ISSUE THREAD

**Issue by katyo** [toby/serde-bencode#13]
I would like to use this library to handle BT DHT messages. I represent some fields (like TransactionId, NodeId) as Vec<u8> but I see that it encoded as arrays of integers, not as byte strings as expected. I don't sure that it is a wrong behavior, but I need a way to fix it.

**Comment by katyo** [comment]
Oh, I already found solution. Please, close this issue.

**Comment by DCjanus** [comment]
Hi, what solution you've found?

**Comment by oreophilum** [comment]
For future reference: You can annotate struct fields with `#[serde(with = "serde_bytes")]` from the [serde_bytes](https://crates.io/crates/serde_bytes)-crate.

For example:

```rust
#[derive(Serialize, Deserialize)]
pub struct File {
    pub length: i64,
    #[serde(rename = "pieces root")]
    #[serde(with = "serde_bytes")]
    pub pieces_root: Vec<u8>,
}
