### ISSUE TITLE
Fix Rust 1.26 attribute regression

### ISSUE THREAD

**Issue by toby** [toby/serde-bencode#15]
From: https://github.com/rust-lang/rust/issues/49934

Looks like Rust 1.26 breaks our build.

**Comment by chpio** [comment]
maybe im just blind, but where's the error: https://cargobomb-reports.s3.amazonaws.com/beta-1.26.0-beta.2/beta-2018-04-06/reg/serde_bencode-0.2.0/log.txt

**Comment by toby** [comment]
@chpio I also didn't parse an error out of that. I was going to build it with 1.26 after work today to see what was up. If nothing else, this ticket can be to go back and tell them there's no problem :)

**Comment by madadam** [comment]
Minimal rust version required by this crate is now 1.40.0. I'm closing this, but feel free to create a new issue if you need it to support older rusts.
