### ISSUE TITLE
Error round-tripping complex struct

### ISSUE THREAD

**Issue by casey** [toby/serde-bencode#17]
I ran into a problem deserializing a complex struct:

```rust
fn ser_de_field_vec_tuple() {
    #[derive(Deserialize, Serialize, Eq, PartialEq, Debug)]
    struct Foo {
        bar: Vec<(u16,)>,
    }

    let foo = Foo {
        bar: vec![(1,), (3,)],
    };

    test_ser_de_eq(foo);
}
```

The error message is `InvalidType("Invalid Type: sequence (expected: `field identifier`)")'`

I wasn't able reduce the test case by removing the struct, the vec, or the tuple, so it seems to be some weird combination of the three.

**Comment by 0xcaff** [comment]
I wonder whether this happens with nested `Vec`'s also.
