### ISSUE TITLE
Upgrade to serde 1.0

### ISSUE THREAD

**Issue by kpcyrd** [toby/serde-bencode#5]
I'm trying to move away from bencode to serde-bencode due to the rustc-serialize deprecation. (https://github.com/kpcyrd/cjdns-rs/issues/2)

Could you please consider upgrading to 1.0 :) ?

**Comment by toby** [comment]
Yes I would like to do this. I was waiting for 1.0 and the Serde API to fully stabilize.

**Comment by chpio** [comment]
Im working on this right now.

ps: kpcyrd there is already a cjdns rust impl (it's early wip) at https://github.com/rust-fcp/ #justsayin

**Comment by toby** [comment]
@chpio I like those suggestions and would merge them.

**Comment by toby** [comment]
@chpio's changes have been merged and an updated crate has been published.

https://github.com/toby/serde-bencode/releases/tag/v0.2.0
