### ISSUE TITLE
Bytebuf with serde-bencode 0.2.0?

### ISSUE THREAD

**Issue by CraigglesO** [toby/serde-bencode#8]
Since we can use serde 1.0 now, can you explain how to use Vec<u8> rather then bytebuf now? I am still getting errors -_-

**Comment by chpio** [comment]
Hmm? If you want a `Vec<u8>` to be serialized to a bytes string and not a sequence of numbers you have to use a `ByteBuf`.

**Comment by CraigglesO** [comment]
Yep. That was exactly it. Can't believe I forgot about the annotation.

Thanks for the help.
